name: workflow nodejs-app

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]  

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Run build task
      run: |
        cd client
        npm install dotenv@latest
        npm install webpack@latest babel-loader@latest babel-core@latest
        npm run build

  test_frontend:
    needs: [build_frontend]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Run frontend test
      run: |
        cd client
        export REACT_APP_API_URL='http://localhost:9000/testAPI'
        npm run test

  test_backend:
    needs: [build_frontend]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        cd api
        npm install

    - name: Run backend test
      run: |
        cd api
        npm run test